import request from 'supertest';
import { buildApp } from '../server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

describe('Clients API', () => {
  let app: any; // FastifyInstance

  beforeAll(async () => {
    app = await buildApp();
    await app.ready();
  });

  afterAll(async () => {
    await app.close();
    await prisma.$disconnect(); // Disconnect PrismaClient
  });

  beforeEach(async () => {
    // Clean the database before each test
    await prisma.client.deleteMany({});
  });

  describe('POST /clients', () => {
    test('should create a new client', async () => {
      const newClient = {
        name: 'John Doe',
        email: 'john.doe@example.com',
        // Removed phone, address, birthDate
        age: 30,
        status: 'Active',
        totalPatrimony: 100000.00,
      };

      const response = await request(app.server)
        .post('/clients')
        .send(newClient);

      expect(response.statusCode).toBe(201);
      expect(response.body).toEqual(expect.objectContaining({
        id: expect.any(String), // ID will be generated by Prisma
        name: newClient.name,
        email: newClient.email,
      }));

      // Verify client was actually created in the database
      const createdClientInDb = await prisma.client.findUnique({
        where: { id: response.body.id },
      });
      expect(createdClientInDb).not.toBeNull();
      expect(createdClientInDb?.email).toBe(newClient.email);
    });

    test('should return 400 if required fields are missing', async () => {
      const invalidClient = {
        name: 'Jane Doe',
        // email is missing
      };

      const response = await request(app.server)
        .post('/clients')
        .send(invalidClient);

      expect(response.statusCode).toBe(400);
      expect(response.body).toHaveProperty('message');
    });
  });

  describe('GET /clients', () => {
    test('should return a list of clients', async () => {
      const client1 = await prisma.client.create({
        data: {
          name: 'John Doe',
          email: 'john.doe@example.com',
          // Removed phone, address, birthDate
          age: 30,
          status: 'Active',
          totalPatrimony: 100000.00,
        },
      });

      const client2 = await prisma.client.create({
        data: {
          name: 'Jane Smith',
          email: 'jane.smith@example.com',
          // Removed phone, address, birthDate
          age: 25,
          status: 'Inactive',
          totalPatrimony: 150000.00,
        },
      });

      const response = await request(app.server).get('/clients');

      expect(response.statusCode).toBe(200);
      expect(response.body).toHaveLength(2);
      expect(response.body).toEqual(expect.arrayContaining([
        expect.objectContaining({ id: client1.id, email: client1.email }),
        expect.objectContaining({ id: client2.id, email: client2.email }),
      ]));
    });

    test('should return an empty array if no clients exist', async () => {
      const response = await request(app.server).get('/clients');

      expect(response.statusCode).toBe(200);
      expect(response.body).toEqual([]);
    });
  });

  describe('GET /clients/:id', () => {
    test('should return a client by ID', async () => {
      const client = await prisma.client.create({
        data: {
          name: 'John Doe',
          email: 'john.doe@example.com',
          // Removed phone, address, birthDate
          age: 30,
          status: 'Active',
          totalPatrimony: 100000.00,
        },
      });

      const response = await request(app.server).get(`/clients/${client.id}`);

      expect(response.statusCode).toBe(200);
      expect(response.body).toEqual(expect.objectContaining({ id: client.id, email: client.email }));
    });

    test('should return 404 if client not found', async () => {
      const nonExistentId = 'some-non-existent-id';
      const response = await request(app.server).get(`/clients/${nonExistentId}`);

      expect(response.statusCode).toBe(404);
      expect(response.body).toHaveProperty('message', 'Client not found');
    });
  });

  describe('PUT /clients/:id', () => {
    test('should update an existing client', async () => {
      const client = await prisma.client.create({
        data: {
          name: 'John Doe',
          email: 'john.doe@example.com',
          // Removed phone, address, birthDate
          age: 30,
          status: 'Active',
          totalPatrimony: 100000.00,
        },
      });

      const updatedClientData = {
        name: 'John Doe Updated',
        // Removed phone
      };

      const response = await request(app.server)
        .put(`/clients/${client.id}`)
        .send(updatedClientData);

      expect(response.statusCode).toBe(200);
      expect(response.body).toEqual(expect.objectContaining({
        id: client.id,
        name: updatedClientData.name,
        // Removed phone assertion
      }));

      // Verify client was actually updated in the database
      const updatedClientInDb = await prisma.client.findUnique({
        where: { id: client.id },
      });
      expect(updatedClientInDb?.name).toBe(updatedClientData.name);
      // Removed phone assertion
    });

    test('should return 404 if client to update is not found', async () => {
      const nonExistentId = 'some-non-existent-id';
      const response = await request(app.server)
        .put(`/clients/${nonExistentId}`)
        .send({ name: 'Non Existent' });

      expect(response.statusCode).toBe(404);
      expect(response.body).toHaveProperty('message', 'Client not found');
    });

    test('should return 400 if invalid data is provided for update', async () => {
      const client = await prisma.client.create({
        data: {
          name: 'John Doe',
          email: 'john.doe@example.com',
          // Removed phone, address, birthDate
          age: 30,
          status: 'Active',
          totalPatrimony: 100000.00,
        },
      });

      const response = await request(app.server)
        .put(`/clients/${client.id}`)
        .send({ email: 'invalid-email' }); // Invalid email format

      expect(response.statusCode).toBe(400);
      expect(response.body).toHaveProperty('message');
    });
  });

  describe('DELETE /clients/:id', () => {
    test('should delete a client', async () => {
      const client = await prisma.client.create({
        data: {
          name: 'John Doe',
          email: 'john.doe@example.com',
          // Removed phone, address, birthDate
          age: 30,
          status: 'Active',
          totalPatrimony: 100000.00,
        },
      });

      const response = await request(app.server).delete(`/clients/${client.id}`);

      expect(response.statusCode).toBe(204);

      // Verify client was actually deleted from the database
      const deletedClientInDb = await prisma.client.findUnique({
        where: { id: client.id },
      });
      expect(deletedClientInDb).toBeNull();
    });

    test('should return 404 if client to delete is not found', async () => {
      const nonExistentId = 'some-non-existent-id';
      const response = await request(app.server).delete(`/clients/${nonExistentId}`);

      expect(response.statusCode).toBe(404);
      expect(response.body).toHaveProperty('message', 'Client not found');
    });
  });
});